---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность оформлять заказ с переходом на страницу оплаты
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Интерфейс должен быть интуитивно понятным и удобным для пользователя
  - Должна быть обеспечена доступность для людей с ограниченными возможностями
  - Необходимо обеспечить быстрое время загрузки страниц
  - Корзина должна быть легко доступной из любого места сайта
  - На всех страницах должна быть единообразная навигация
  - Сообщения об ошибках должны быть понятными и информативными
  - Поддержка локализации и мультиязычности
