functional:
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен быть доступен на различных устройствах
non-functional: 
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Сайт должен отображать картинку флага страны при выборе языка
  - Сайт должен автоматически менять категорию товара при выборе следующей странице
  - Сайт должен автоматически менять производителей товарой при выборе категории
  - После успешного оформления заказа, у пользователя должна очищаться корзина автоматически
  - Пользователь должен иметь возможность при добавлении товаров в корзину указывать количество которое пользователь хочет заказать
  - У сайта должна быть функция создания профиля с обязательными полями: Логин, пароль, телефон, email. Для того чтобы при оформлении заказа было понятно куда делать обратную связь.
  - Сумма товаров в корзине должен считаться корректно и правильно.
  - На сайте должно меняться описание товаров на тот язык который выбран в данный момент
